Process Class Reference
#include <tl.h>
Public Member Functions
Process ()
string getName ()
void setName (string x)
int getId ()
void setId (int x)
int getPriority ()
void setPriority (int x)
int getCriticality ()
void setCriticality (int x)
float getEqGate ()
void setEqGate (float g)
int getDataType ()
void setDataType (int x)
void setMemSize (Memory m)
void setCodeSize (string procName, unsigned int value)
void setDataSize (string procName, unsigned int value)
float getAffinityByName (string processorName)
void setAffinity (string processorName, float affinity)
void setConcurrency (int procId, float conc)
void setLoad (int procId, float value)
int getPS_Profiling ()
sc_time getProcessTime ()
void setEnergy (float energy)
float getEnergy ()
Data Fields
string name
unsigned int id
unsigned int priority
unsigned int criticality
float eqGate
unsigned int dataType
map< string, unsigned int > codeSizeMap
map< string, unsigned int > dataSizeMap
map< string, float > affinity
map< int, float > concurrency
map< int, float > load
unsigned int profiling
sc_time processTime
float energy
Detailed Description
Definition at line 161 of file tl.h.
Constructor & Destructor Documentation
Process()
Process::Process ()
Definition at line 311 of file tl.cpp.
                {
    id = 0;
    eqGate = 0;
    dataType = 0;
    criticality = 0;
    profiling = 0;
    processTime = sc_time(0, SC_MS);
    priority = 0;
    energy = 0;
}
Member Function Documentation
getAffinityByName()
float Process::getAffinityByName (string processorName)
Definition at line 406 of file tl.cpp.
                                                     {
    map<string, float>::iterator it = this->affinity.find(processorName);
    if (it != this->affinity.end())
        return it->second;
    else
        return 0;
}
getCriticality()
int Process::getCriticality ()
Definition at line 360 of file tl.cpp.
{
    return this->criticality;
}
getDataType()
int Process::getDataType ()
Definition at line 380 of file tl.cpp.
{
    return this->dataType;
}
getEnergy()
float Process::getEnergy ()
Definition at line 342 of file tl.cpp.
                        {
    return this->energy;
}
getEqGate()
float Process::getEqGate ()
Definition at line 370 of file tl.cpp.
{
    return this->eqGate;
}
getId()
int Process::getId ()
Definition at line 332 of file tl.cpp.
{
    return this->id;
}
getName()
string Process::getName ()
Definition at line 322 of file tl.cpp.
{
    return this->name;
}
getPriority()
int Process::getPriority ()
Definition at line 350 of file tl.cpp.
{
    return this->priority;
}
getProcessTime()
sc_time Process::getProcessTime ()
Definition at line 440 of file tl.cpp.
{
    return this->processTime;
}
getPS_Profiling()
int Process::getPS_Profiling ()
Definition at line 435 of file tl.cpp.
{
    return this->profiling;
}
setAffinity()
void Process::setAffinity (string processorName, float affinity)
Definition at line 414 of file tl.cpp.
{
    map <string, float>::iterator end = this->affinity.end();
    pair<string, float> item (x, y);
    this->affinity.insert(end, item);
}
Referenced by SystemManager::generateProcessInstances().
setCodeSize()
void Process::setCodeSize (string procName, unsigned int value)
Definition at line 390 of file tl.cpp.
                                                   {
    map <string, unsigned int>::iterator end = this->codeSizeMap.end();
    pair<string, unsigned int> item (p, mem);
    this->codeSizeMap.insert(end, item);
}
Referenced by SystemManager::generateProcessInstances().
setConcurrency()
void Process::setConcurrency (int procId, float conc)
Definition at line 421 of file tl.cpp.
{
    map <int, float>::iterator end = this->concurrency.end();
    pair<int, float> item (p, c);
    this->concurrency.insert(end, item);
}
Referenced by SystemManager::generateProcessInstances().
setCriticality()
void Process::setCriticality (int x)
Definition at line 365 of file tl.cpp.
{
    criticality = x;
}
Referenced by SystemManager::generateProcessInstances().
setDataSize()
void Process::setDataSize (string procName, unsigned int value)
Definition at line 396 of file tl.cpp.
                                                   {
    map <string, unsigned int>::iterator end = this->dataSizeMap.end();
    pair<string, unsigned int> item (p, mem);
    this->dataSizeMap.insert(end, item);
}
Referenced by SystemManager::generateProcessInstances().
setDataType()
void Process::setDataType (int x)
Definition at line 385 of file tl.cpp.
{
    dataType = x;
}
Referenced by SystemManager::generateProcessInstances().
setEnergy()
void Process::setEnergy (float energy)
Definition at line 346 of file tl.cpp.
                               {
    energy = en;
}
Referenced by SystemManager::generateProcessInstances().
setEqGate()
void Process::setEqGate (float g)
Definition at line 375 of file tl.cpp.
{
    eqGate = g;
}
Referenced by SystemManager::generateProcessInstances().
setId()
void Process::setId (int x)
Definition at line 337 of file tl.cpp.
{
    id = x;
}
Referenced by SystemManager::generateProcessInstances().
setLoad()
void Process::setLoad (int procId, float value)
Definition at line 428 of file tl.cpp.
                                       {
    map <int, float>::iterator end = this->load.end();
    pair<int, float> item (p, value);
    this->load.insert(end, item);
}
Referenced by SystemManager::generateProcessInstances().
setMemSize()
void Process::setMemSize (Memory m)
setName()
void Process::setName (string x)
Definition at line 327 of file tl.cpp.
{
    name = x;
}
Referenced by SystemManager::generateProcessInstances().
setPriority()
void Process::setPriority (int x)
Definition at line 355 of file tl.cpp.
{
    priority = x;
}
Referenced by SystemManager::generateProcessInstances().
Field Documentation
affinity
map<string,float> Process::affinity
Definition at line 173 of file tl.h.
codeSizeMap
map<string, unsigned int> Process::codeSizeMap
Definition at line 170 of file tl.h.
concurrency
map<int,float> Process::concurrency
Definition at line 174 of file tl.h.
criticality
unsigned int Process::criticality
Definition at line 167 of file tl.h.
dataSizeMap
map<string, unsigned int> Process::dataSizeMap
Definition at line 171 of file tl.h.
dataType
unsigned int Process::dataType
Definition at line 169 of file tl.h.
energy
float Process::energy
Definition at line 178 of file tl.h.
eqGate
float Process::eqGate
Definition at line 168 of file tl.h.
id
unsigned int Process::id
Definition at line 165 of file tl.h.
load
map<int,float> Process::load
Definition at line 175 of file tl.h.
name
string Process::name
Definition at line 164 of file tl.h.
priority
unsigned int Process::priority
Definition at line 166 of file tl.h.
processTime
sc_time Process::processTime
Definition at line 177 of file tl.h.
Referenced by SystemManager::generateProcessInstances().
profiling
unsigned int Process::profiling
Definition at line 176 of file tl.h.
The documentation for this class was generated from the following files:
HepsycodeDesign/src/tl.h
HepsycodeDesign/src/tl.cpp