BasicBlock Class Reference
#include <tl.h>
Public Member Functions
string getName ()
void setName (string x)
int getId ()
void setId (int x)
string getType ()
void setType (string x)
int getIdPU ()
void setIdPU (int x)
vector< ProcessingUnit > getProcessors ()
void setProcessor (vector< ProcessingUnit > pu)
unsigned int getCodeSize ()
void setCodeSize (unsigned int c)
unsigned int getDataSize ()
void setDataSize (unsigned int c)
unsigned int getEqG ()
void setEqG (unsigned int c)
float getFRT ()
void setFRT (float x)
Private Attributes
string name
unsigned int id
string type
int idPU
vector< ProcessingUnit > vpu
unsigned int codeSize
unsigned int dataSize
unsigned int eqG
float FRT
Detailed Description
Definition at line 219 of file tl.h.
Member Function Documentation
getCodeSize()
unsigned int BasicBlock::getCodeSize ()
Definition at line 277 of file tl.cpp.
                                    {
    return this->codeSize;
}
getDataSize()
unsigned int BasicBlock::getDataSize ()
Definition at line 285 of file tl.cpp.
                                    {
    return this->dataSize;
}
getEqG()
unsigned int BasicBlock::getEqG ()
Definition at line 293 of file tl.cpp.
                               {
    return this->eqG;
}
getFRT()
float BasicBlock::getFRT ()
Definition at line 305 of file tl.cpp.
                         {
    return FRT;
}
getId()
int BasicBlock::getId ()
Definition at line 229 of file tl.cpp.
{
    return this->id;
}
getIdPU()
int BasicBlock::getIdPU ()
Definition at line 250 of file tl.cpp.
{
    return this->idPU;
}
getName()
string BasicBlock::getName ()
Definition at line 219 of file tl.cpp.
{
    return this->name;
}
getProcessors()
vector< ProcessingUnit > BasicBlock::getProcessors ()
Definition at line 271 of file tl.cpp.
{
    return vpu;
}
getType()
string BasicBlock::getType ()
Definition at line 239 of file tl.cpp.
{
    return type;
}
setCodeSize()
void BasicBlock::setCodeSize (unsigned int c)
Definition at line 281 of file tl.cpp.
                                          {
    this->codeSize = c;
}
Referenced by SystemManager::generateBBInstances().
setDataSize()
void BasicBlock::setDataSize (unsigned int c)
Definition at line 289 of file tl.cpp.
                                          {
    this->dataSize = d;
}
Referenced by SystemManager::generateBBInstances().
setEqG()
void BasicBlock::setEqG (unsigned int c)
Definition at line 297 of file tl.cpp.
                                     {
    this->eqG = e;
}
Referenced by SystemManager::generateBBInstances().
setFRT()
void BasicBlock::setFRT (float x)
Definition at line 301 of file tl.cpp.
                               {
    FRT = x;
}
Referenced by SystemManager::generateBBInstances().
setId()
void BasicBlock::setId (int x)
Definition at line 234 of file tl.cpp.
{
    id = x;
}
Referenced by SystemManager::generateBBInstances().
setIdPU()
void BasicBlock::setIdPU (int x)
Definition at line 255 of file tl.cpp.
{
    idPU = x;
}
setName()
void BasicBlock::setName (string x)
Definition at line 224 of file tl.cpp.
{
    name = x;
}
Referenced by SystemManager::generateBBInstances().
setProcessor()
void BasicBlock::setProcessor (vector< ProcessingUnit > pu)
Definition at line 260 of file tl.cpp.
{
    vpu= p;
}
Referenced by SystemManager::generateBBInstances().
setType()
void BasicBlock::setType (string x)
Definition at line 245 of file tl.cpp.
{
    type = x;
}
Referenced by SystemManager::generateBBInstances().
Field Documentation
codeSize
unsigned int BasicBlock::codeSize [private]
Definition at line 229 of file tl.h.
dataSize
unsigned int BasicBlock::dataSize [private]
Definition at line 230 of file tl.h.
eqG
unsigned int BasicBlock::eqG [private]
Definition at line 231 of file tl.h.
FRT
float BasicBlock::FRT [private]
Definition at line 232 of file tl.h.
id
unsigned int BasicBlock::id [private]
Definition at line 223 of file tl.h.
idPU
int BasicBlock::idPU [private]
Definition at line 225 of file tl.h.
name
string BasicBlock::name [private]
Definition at line 222 of file tl.h.
type
string BasicBlock::type [private]
Definition at line 224 of file tl.h.
vpu
vector<ProcessingUnit> BasicBlock::vpu [private]
Definition at line 226 of file tl.h.
The documentation for this class was generated from the following files:
HepsycodeDesign/src/tl.h
HepsycodeDesign/src/tl.cpp