.TH "HepsycodeDesign/src/processesInstr Directory Reference" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/processesInstr Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfir16_evaluation\&.cpp\fP"
.br
.RI "FIR16 Evaluation Documented file\&. "
.ti -1c
.RI "file \fBfir16_main\&.cpp\fP"
.br
.RI "FIR16 Documented file\&. "
.ti -1c
.RI "file \fBfir16_shifting\&.cpp\fP"
.br
.RI "FIR16 Shifting Documented file\&. "
.ti -1c
.RI "file \fBfir8_evaluation\&.cpp\fP"
.br
.RI "FIR8 Evaluation Documented file\&. "
.ti -1c
.RI "file \fBfir8_main\&.cpp\fP"
.br
.RI "FIR8 Documented file\&. "
.ti -1c
.RI "file \fBfir8_shifting\&.cpp\fP"
.br
.RI "FIR8 Shifting Documented file\&. "
.ti -1c
.RI "file \fBgcd_evaluation\&.cpp\fP"
.br
.RI "GCD Evaluation Documented file\&. "
.ti -1c
.RI "file \fBgcd_main\&.cpp\fP"
.br
.RI "GCD Documented file\&. "
.in -1c
