.TH "HepsycodeDesign/src/display.cpp" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/display.cpp \- Display Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'display\&.h'\fP
.br
\fC#include 'define\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Display Documented file\&. 

Display module: SystemC Module specifying the functionality of the Display component 
.PP
Definition in file \fBdisplay\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
