.TH "fir16e_parameters" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fir16e_parameters \- Message from fir16m to fir16e\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatype\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_uint< 19 > \fBacc\fP"
.br
.ti -1c
.RI "sc_uint< 9 > \fBcoef\fP [16]"
.br
.ti -1c
.RI "sc_uint< 8 > \fBshift\fP [16]"
.br
.ti -1c
.RI "sc_uint< 8 > \fBsample_tmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message from fir16m to fir16e\&. 
.PP
Definition at line 144 of file datatype\&.h\&.
.SH "Field Documentation"
.PP 
.SS "sc_uint<19> fir16e_parameters::acc"

.PP
Definition at line 148 of file datatype\&.h\&.
.SS "sc_uint<9> fir16e_parameters::coef[16]"

.PP
Definition at line 149 of file datatype\&.h\&.
.SS "sc_uint<8> fir16e_parameters::sample_tmp"

.PP
Definition at line 151 of file datatype\&.h\&.
.SS "sc_uint<8> fir16e_parameters::shift[16]"

.PP
Definition at line 150 of file datatype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
