.TH "fir16s_parameters" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fir16s_parameters \- Message from fir16m to fir16s\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatype\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_uint< 8 > \fBshift\fP [16]"
.br
.ti -1c
.RI "sc_uint< 8 > \fBsample_tmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message from fir16m to fir16s\&. 
.PP
Definition at line 159 of file datatype\&.h\&.
.SH "Field Documentation"
.PP 
.SS "sc_uint<8> fir16s_parameters::sample_tmp"

.PP
Definition at line 162 of file datatype\&.h\&.
.SS "sc_uint<8> fir16s_parameters::shift[16]"

.PP
Definition at line 161 of file datatype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
