.TH "HepsycodeDesign/src/processesInstr/fir8_main.cpp" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/processesInstr/fir8_main.cpp \- FIR8 Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mainsystem\&.h'\fP
.br

.SH "Detailed Description"
.PP 
FIR8 Documented file\&. 

FIR_8 process: CSP \fBProcess\fP specifying the functionality of the FIR8 component\&. 
.PP
Definition in file \fBfir8_main\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
