.TH "HepsycodeDesign/src/processesInstr/fir8_shifting.cpp" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/processesInstr/fir8_shifting.cpp \- FIR8 Shifting Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mainsystem\&.h'\fP
.br

.SH "Detailed Description"
.PP 
FIR8 Shifting Documented file\&. 

FIR_8 Shifting process: CSP \fBProcess\fP specifying the functionality of the FIR8 Shifting component 
.PP
Definition in file \fBfir8_shifting\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
