.TH "fir8e_parameters" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fir8e_parameters \- Message from fir8m to fir8e\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'src/datatype\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_uint< 19 > \fBacc\fP"
.br
.RI "Example 1\&. "
.ti -1c
.RI "sc_uint< 9 > \fBcoef\fP [8]"
.br
.RI "Example 2\&. "
.ti -1c
.RI "sc_uint< 8 > \fBshift\fP [8]"
.br
.ti -1c
.RI "sc_uint< 8 > \fBsample_tmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message from fir8m to fir8e\&. 

struct \fBfir8e_parameters\fP
.PP
Some details about the \fBfir8e_parameters\fP struct\&. 
.br

.PP
Definition at line 94 of file datatype\&.h\&.
.SH "Field Documentation"
.PP 
.SS "sc_uint<19> fir8e_parameters::acc"

.PP
Example 1\&. 
.PP
Definition at line 96 of file datatype\&.h\&.
.SS "sc_uint<9> fir8e_parameters::coef[8]"

.PP
Example 2\&. 
.PP
Definition at line 97 of file datatype\&.h\&.
.SS "sc_uint<8> fir8e_parameters::sample_tmp"
Example 4\&. 
.PP
Definition at line 99 of file datatype\&.h\&.
.SS "sc_uint<8> fir8e_parameters::shift[8]"
Example 3\&. 
.PP
Definition at line 98 of file datatype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
