.TH "fir8s_parameters" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fir8s_parameters \- struct \fBfir8s_parameters\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'src/datatype\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_uint< 8 > \fBshift\fP [8]"
.br
.ti -1c
.RI "sc_uint< 8 > \fBsample_tmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBfir8s_parameters\fP 

Some details about the \fBfir8s_parameters\fP struct\&. 
.br
Message from fir8m to fir8s 
.PP
Definition at line 121 of file datatype\&.h\&.
.SH "Field Documentation"
.PP 
.SS "sc_uint<8> fir8s_parameters::sample_tmp"

.PP
Definition at line 124 of file datatype\&.h\&.
.SS "sc_uint<8> fir8s_parameters::shift[8]"

.PP
Definition at line 123 of file datatype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
