.TH "firfirgcd_datatypes_group" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
firfirgcd_datatypes_group \- DATATYPES (i\&.e\&., MESSAGES) USED BY THE CHANNELS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBfir8e_parameters\fP"
.br
.RI "Message from fir8m to fir8e\&. "
.ti -1c
.RI "struct \fBfir8e_results\fP"
.br
.RI "struct \fBfir8e_results\fP "
.ti -1c
.RI "struct \fBfir8s_parameters\fP"
.br
.RI "struct \fBfir8s_parameters\fP "
.ti -1c
.RI "struct \fBfir8s_results\fP"
.br
.RI "struct \fBfir8s_results\fP "
.ti -1c
.RI "struct \fBfir16e_parameters\fP"
.br
.RI "Message from fir16m to fir16e\&. "
.ti -1c
.RI "struct \fBfir16e_results\fP"
.br
.RI "Message from fir16e to fir16m\&. "
.ti -1c
.RI "struct \fBfir16s_parameters\fP"
.br
.RI "Message from fir16m to fir16s\&. "
.ti -1c
.RI "struct \fBfir16s_results\fP"
.br
.RI "Message from fir16s to fir16m\&. "
.ti -1c
.RI "struct \fBgcde_parameters\fP"
.br
.RI "Message from gcdm to gcde\&. "
.ti -1c
.RI "struct \fBgcde_results\fP"
.br
.RI "Message from gcde to gcdm\&. "
.in -1c
.SH "Detailed Description"
.PP 
DATATYPES (i\&.e\&., MESSAGES) USED BY THE CHANNELS\&. 

Defines all the FirFirGCD related datatypes 
.PP
\fBAuthor\fP
.RS 4
V\&. Muttillo, L\&. Pomante 
.RE
.PP
\fBDate\fP
.RS 4
Apr\&. 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
