.TH "HepsycodeDesign/src/processesInstr/gcd_main.cpp" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/processesInstr/gcd_main.cpp \- GCD Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mainsystem\&.h'\fP
.br

.SH "Detailed Description"
.PP 
GCD Documented file\&. 

GCD process: CSP \fBProcess\fP specifying the functionality of the GCD component\&. 
.PP
Definition in file \fBgcd_main\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
