.TH "gcde_parameters" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gcde_parameters \- Message from gcdm to gcde\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatype\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sc_uint< 8 > \fBsample1\fP"
.br
.ti -1c
.RI "sc_uint< 8 > \fBsample2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message from gcdm to gcde\&. 
.PP
Definition at line 176 of file datatype\&.h\&.
.SH "Field Documentation"
.PP 
.SS "sc_uint<8> gcde_parameters::sample1"

.PP
Definition at line 180 of file datatype\&.h\&.
.SS "sc_uint<8> gcde_parameters::sample2"

.PP
Definition at line 181 of file datatype\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
