.TH "HepsycodeDesign/src/mainsystem.h" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/mainsystem.h \- Mainsystem Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'define\&.h'\fP
.br
\fC#include 'sc_csp_channel_ifs\&.h'\fP
.br
\fC#include 'sc_csp_channel\&.h'\fP
.br
\fC#include 'datatype\&.h'\fP
.br
\fC#include 'SystemManager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_MODULE\fP (mainsystem)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mainsystem Documented file\&. 

Details\&. 
.PP
Definition in file \fBmainsystem\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
