.TH "HepsycodeDesign/src/main.cpp" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/main.cpp \- Main Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <systemc\&.h>\fP
.br
\fC#include 'define\&.h'\fP
.br
\fC#include 'sc_csp_channel_ifs\&.h'\fP
.br
\fC#include 'datatype\&.h'\fP
.br
\fC#include 'stim_gen\&.h'\fP
.br
\fC#include 'mainsystem\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'sc_csp_channel\&.h'\fP
.br
\fC#include 'SchedulingManager\&.h'\fP
.br
\fC#include 'SystemManager\&.h'\fP
.br
\fC#include 'tl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsc_main\fP (int a, char *b[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSystemManager\fP * \fBpSystemManager\fP = new \fBSystemManager\fP()"
.br
.ti -1c
.RI "SchedulingManager * \fBpSchedulingManager\fP = new SchedulingManager('SchedulingManager')"
.br
.ti -1c
.RI "unsigned int \fBsampling_period\fP = 1000"
.br
.ti -1c
.RI "bool \fBstop_concurrency_sampling\fP =false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main Documented file\&. 

Details\&. 
.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
