.TH "HepsycodeDesign/src/sc_csp_channel_ifs.h" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/sc_csp_channel_ifs.h \- The sc_csp_channel<T> interface classes documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sysc/communication/sc_interface\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_csp_channel_in_if< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_csp_channel_out_if< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsc_core\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The sc_csp_channel<T> interface classes documented file\&. 

Details\&. 
.PP
Definition in file \fBsc_csp_channel_ifs\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
