.TH "HepsycodeDesign/src/sc_csp_channel.h" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/sc_csp_channel.h \- The sc_csp_channel<T> primitive channel class documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sysc/communication/sc_communication_ids\&.h'\fP
.br
\fC#include 'sysc/communication/sc_prim_channel\&.h'\fP
.br
\fC#include 'sysc/kernel/sc_event\&.h'\fP
.br
\fC#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br
\fC#include 'sysc/tracing/sc_trace\&.h'\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include 'sc_csp_channel_ifs\&.h'\fP
.br
\fC#include 'define\&.h'\fP
.br
\fC#include 'SystemManager\&.h'\fP
.br
\fC#include 'SchedulingManager\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBsc_csp_channel< T >\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSystemManager\fP * \fBpSystemManager\fP"
.br
.ti -1c
.RI "SchedulingManager * \fBpSchedulingManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The sc_csp_channel<T> primitive channel class documented file\&. 

Details\&. 
.PP
Definition in file \fBsc_csp_channel\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
