.TH "sc_core" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBsc_csp_channel_in_if\fP"
.br
.ti -1c
.RI "class \fBsc_csp_channel_out_if\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
