.TH "sc_interface" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_interface
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsc_core::sc_csp_channel_in_if< T >\fP\fC [virtual]\fP, and \fBsc_core::sc_csp_channel_out_if< T >\fP\fC [virtual]\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
