.TH "HepsycodeDesign/src/stim_gen.h" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/stim_gen.h \- Stimulus Generation Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <systemc\&.h>\fP
.br
\fC#include 'sc_csp_channel_ifs\&.h'\fP
.br
\fC#include 'define\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_MODULE\fP (stim_gen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stimulus Generation Documented file\&. 

Details\&. 
.PP
Definition in file \fBstim_gen\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
