.TH "HepsycodeDesign/src/SystemManager.cpp" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/SystemManager.cpp \- System Manager Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <systemc\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'tl\&.h'\fP
.br
\fC#include 'pugixml\&.hpp'\fP
.br
\fC#include 'SystemManager\&.h'\fP
.br

.SH "Detailed Description"
.PP 
System Manager Documented file\&. 

System Manager: HEPSIM System Manager\&. 
.PP
Definition in file \fBSystemManager\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
