.TH "HepsycodeDesign/src/tl.h" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HepsycodeDesign/src/tl.h \- HEPSIM Technologies Library Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <systemc\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <set>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBProcessingUnit\fP"
.br
.ti -1c
.RI "class \fBMemory\fP"
.br
.ti -1c
.RI "class \fBProcess\fP"
.br
.ti -1c
.RI "class \fBBasicBlock\fP"
.br
.ti -1c
.RI "class \fBPhysicalLink\fP"
.br
.ti -1c
.RI "class \fBChannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HEPSIM Technologies Library Documented file\&. 

Technologies Library: Technologies Library file 
.PP
Definition in file \fBtl\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
