.TH "tl_group" 3 "Mon Mar 20 2023" "FirFirGCD Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tl_group \- Technologies Library Implementation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBProcessingUnit\fP"
.br
.ti -1c
.RI "class \fBMemory\fP"
.br
.ti -1c
.RI "class \fBProcess\fP"
.br
.ti -1c
.RI "class \fBBasicBlock\fP"
.br
.ti -1c
.RI "class \fBPhysicalLink\fP"
.br
.ti -1c
.RI "class \fBChannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Technologies Library Implementation\&. 


.PP
\fBAuthor\fP
.RS 4
V\&. Muttillo, L\&. Pomante 
.RE
.PP
\fBDate\fP
.RS 4
Apr\&. 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FirFirGCD Application from the source code\&.
